name: Rust

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
        rust:
          - stable
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: ${{ matrix.rust }}
      - name: Install Cargo Bundle
        run: cargo install cargo-bundle
      - name: Build
        run: cargo build --release
      - name: Bundle
        run: cargo bundle --release
      - uses: actions/upload-artifact@v4
        with:
          name: Bundles
          path: target/release/bundle/**/
